apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
      app: deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: deploy
  template:
    metadata:
      name: nginx-pod
      labels:
        app: deploy
    spec:
      containers:
      - name: nginx-container
        image: nginx
